# Generated by Django 2.2.3 on 2019-12-26 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('buy_user', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='buy_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='is_sold',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='sell_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='hi', max_length=500),
        ),
    ]
