# Generated by Django 2.2.3 on 2019-12-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191226_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_sold',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='buy_user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sell_user',
        ),
    ]
