# Generated by Django 3.0.1 on 2019-12-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191226_2046'),
        ('post', '0004_auto_20191226_1734'),
    ]

    operations = [
    ]
