# Generated by Django 3.0.1 on 2019-12-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
